"""split upload files into name and data

Revision ID: 195d1a723edb
Revises: 1831fc5afe1e
Create Date: 2022-04-07 06:17:55.112669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195d1a723edb'
down_revision = '1831fc5afe1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supportzip_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('supportzip_filename', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('code_scorer_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('code_scorer_filename', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dockerfile_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('dockerfile_filename', sa.String(length=50), nullable=True))
        batch_op.drop_column('dockerfile')
        batch_op.drop_column('code_scoring')
        batch_op.drop_column('support_zip_file')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_filename', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('code_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('code_output_filename', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('code_output_data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('code_file')
        batch_op.drop_column('code_output')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_output', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('code_file', sa.BLOB(), nullable=True))
        batch_op.drop_column('code_output_data')
        batch_op.drop_column('code_output_filename')
        batch_op.drop_column('code_data')
        batch_op.drop_column('code_filename')

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_zip_file', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('code_scoring', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('dockerfile', sa.BLOB(), nullable=True))
        batch_op.drop_column('dockerfile_filename')
        batch_op.drop_column('dockerfile_data')
        batch_op.drop_column('code_scorer_filename')
        batch_op.drop_column('code_scorer_data')
        batch_op.drop_column('supportzip_filename')
        batch_op.drop_column('supportzip_data')

    # ### end Alembic commands ###
