"""Added contest fk to teams

Revision ID: 1d4426565f7b
Revises: 195d1a723edb
Create Date: 2022-04-10 20:12:30.865575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4426565f7b'
down_revision = '195d1a723edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_team')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contest_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_team_contest_id_contest'), 'contest', ['contest_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_team_contest_id_contest'), type_='foreignkey')
        batch_op.drop_column('contest_id')

    op.create_table('_alembic_tmp_team',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contest_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], name='fk_team_contest_id_contest'),
    sa.PrimaryKeyConstraint('id', name='pk_team')
    )
    # ### end Alembic commands ###
