"""added challenge columns

Revision ID: 223a13a1733d
Revises: 8024df43d1b5
Create Date: 2022-04-03 20:24:53.252501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223a13a1733d'
down_revision = '8024df43d1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('files', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('files')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
