"""Added association tables for many to many

Revision ID: def2c539e28e
Revises: 1d4426565f7b
Create Date: 2022-04-12 16:54:26.695627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def2c539e28e'
down_revision = '1d4426565f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_participation',
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], name=op.f('fk_contest_participation_contest_id_contest')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_contest_participation_user_id_user'))
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_members_team_id_team')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_team_members_user_id_user'))
    )
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_team_team', type_='foreignkey')
        batch_op.drop_column('team')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_team_team', 'team', ['team'], ['id'])

    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.drop_column('active')

    op.drop_table('team_members')
    op.drop_table('contest_participation')
    # ### end Alembic commands ###
